// NativeActivity entry point: a thin host for the ported EdgeTX simulator, plus
// the JNI entry points RcLinkService uses to own the firmware.
//
// Everything the user sees is the real EdgeTX firmware running inside
// libedgetx-<flavour>-simulator.so. This file:
//   * owns the *link* - the firmware, the external-module serial bridge and the
//     timer that keeps feeding both. RcLinkService (a foreground service) starts
//     it and keeps the process alive, so the link outlives the UI: that is what
//     makes stick/switch data keep reaching the external RF module after the app
//     is closed,
//   * attaches the activity's window to that link while the UI is on screen and
//     blits the firmware's LCD frames to it,
//   * forwards touch events into the firmware as LCD coordinates.
//
// See simu_host.{h,cpp} for the firmware lifecycle, and
// radio/src/targets/simu/simulib.h for the platform API being used.
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android_native_app_glue.h>
#include <dirent.h>
#include <jni.h>
#include <sys/stat.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include "joystick.h"
#include "log.h"
#include "module_serial.h"
#include "sdcard_manifest.h"  // generated by CMake from assets/sdcard
#include "simu_host.h"

namespace {

constexpr int32_t kFp = 1024;  // fixed-point scale denominator

struct android_app* g_app = nullptr;

// Set by the activity thread while a window is up, cleared when it goes away.
std::atomic<ANativeWindow*> g_window{nullptr};

// Guards the activity's side of the link: the window, the frame buffers and the
// transform, plus the render step itself. Everything in there normally runs on the
// activity thread; the mutex is what keeps the service's thread (link_start /
// link_stop) out of a render that is already in flight.
std::mutex g_renderMutex;

int32_t g_lcdW = 0;
int32_t g_lcdH = 0;

// LCD -> window mapping. Activity thread only.
int32_t g_scaleFP = kFp;
int32_t g_scaledW = 0;
int32_t g_offX = 0;
int32_t g_offY = 0;
std::vector<int32_t> g_srcX;

std::vector<uint16_t> g_frame;  // LCD frame buffer (RGB565), activity thread only

// ---------------------------------------------------------------------------
// The link host: firmware + external module bridge, deliberately independent of
// the activity's window.
//
// RcLinkService starts this and keeps the process alive with a foreground
// service, so the mixer keeps producing module frames with no UI on screen. The
// activity attaches a window to it while it is visible and detaches it when it
// goes away - neither starts nor stops the firmware.
// ---------------------------------------------------------------------------
std::mutex g_linkMutex;
std::thread g_linkThread;
std::atomic<bool> g_linkStop{false};
std::atomic<bool> g_linkRunning{false};

// True while a foreground service is holding the process open for the link. When
// it is clear, the firmware stops with the activity, i.e. the pre-service
// behaviour is kept for the case where the service could not be started.
std::atomic<bool> g_keepAlive{false};

void sleep_ms(uint32_t ms) {
    std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

void ensure_dir(const std::string& path) {
    if (!path.empty()) mkdir(path.c_str(), 0700);
}

// mkdir -p for the slash separated parents of `path`.
void ensure_parent_dirs(const std::string& path) {
    for (size_t i = 1; i < path.size(); ++i) {
        if (path[i] == '/') mkdir(path.substr(0, i).c_str(), 0700);
    }
}

// Copy the bundled SD-card content into the card root, without touching what is
// already there.
//
// The card belongs to the user: models, radio.yml and anything edited by hand live
// in it, and the firmware writes to it as well (LOGS/, screenshots). So a file
// that exists and has content is never overwritten - only missing files (and
// zero-length ones, i.e. an interrupted copy) are written. Delete a file, or the
// whole folder, and relaunch to get the bundled version back.
void seed_assets(AAssetManager* mgr, const std::string& sdRoot) {
    unsigned copied = 0;
    unsigned kept = 0;

    for (unsigned i = 0; i < kSdcardAssetCount; ++i) {
        const std::string rel = kSdcardAssets[i];
        const std::string assetPath = "sdcard/" + rel;
        const std::string outPath = sdRoot + "/" + rel;

        AAsset* asset = AAssetManager_open(mgr, assetPath.c_str(), AASSET_MODE_STREAMING);
        if (asset == nullptr) {
            LOGE("asset missing: %s", assetPath.c_str());
            continue;
        }

        const off_t size = AAsset_getLength(asset);

        struct stat st;
        if (stat(outPath.c_str(), &st) == 0 && st.st_size > 0) {
            AAsset_close(asset);
            ++kept;
            continue;
        }

        ensure_parent_dirs(outPath);

        std::vector<uint8_t> buf(size > 0 ? static_cast<size_t>(size) : 0);
        const int got = size > 0 ? AAsset_read(asset, buf.data(), static_cast<size_t>(size)) : 0;
        AAsset_close(asset);

        FILE* out = std::fopen(outPath.c_str(), "wb");
        if (out == nullptr) {
            LOGE("cannot write %s", outPath.c_str());
            continue;
        }
        if (got > 0) std::fwrite(buf.data(), 1, static_cast<size_t>(got), out);
        std::fclose(out);
        ++copied;
    }

    LOGI("sdcard: %u copied, %u kept, %u bundled", copied, kept, kSdcardAssetCount);
}

// ------------------------------------------------------------- SD card root --
//
// The simulated SD card lives in the app's *external* files directory whenever the
// device has one:
//
//     /sdcard/Android/data/com.edgetx.droidui/files/sdcard
//
// It is the same tree a real radio has on its card, but unlike the app-private
// directory this path needs no permission at all and can be browsed and edited
// over adb (or with a file manager on older Androids), which is the whole point:
//
//     adb push main.lua /sdcard/Android/data/com.edgetx.droidui/files/sdcard/SCRIPTS/
//     adb pull /sdcard/Android/data/com.edgetx.droidui/files/sdcard/RADIO/radio.yml .
//
// The internal directory stays as the fallback for devices without external
// storage, and a card that already lives there is copied over on first run so
// models and calibration survive the move.
const char* const kSdcardSubdir = "/sdcard";

bool file_has_content(const std::string& path) {
    struct stat st;
    return stat(path.c_str(), &st) == 0 && S_ISREG(st.st_mode) && st.st_size > 0;
}

bool copy_file(const std::string& from, const std::string& to) {
    FILE* in = std::fopen(from.c_str(), "rb");
    if (in == nullptr) return false;

    FILE* out = std::fopen(to.c_str(), "wb");
    if (out == nullptr) {
        std::fclose(in);
        return false;
    }

    std::vector<char> buffer(64 * 1024);
    bool ok = true;
    size_t n = 0;
    while ((n = std::fread(buffer.data(), 1, buffer.size(), in)) > 0) {
        if (std::fwrite(buffer.data(), 1, n, out) != n) {
            ok = false;
            break;
        }
    }
    if (std::ferror(in)) ok = false;

    std::fclose(out);
    std::fclose(in);
    return ok;
}

// Copies the files under `from` that `to` does not have yet. Missing directories
// are silently ignored, which is what makes this safe to call on the old card
// location before it exists.
unsigned copy_missing_tree(const std::string& from, const std::string& to) {
    DIR* dir = opendir(from.c_str());
    if (dir == nullptr) return 0;

    unsigned copied = 0;
    const struct dirent* entry = nullptr;
    while ((entry = readdir(dir)) != nullptr) {
        const std::string name = entry->d_name;
        if (name == "." || name == "..") continue;

        const std::string src = from + "/" + name;
        const std::string dst = to + "/" + name;

        struct stat st;
        if (stat(src.c_str(), &st) != 0) continue;

        if (S_ISDIR(st.st_mode)) {
            ensure_dir(dst);
            copied += copy_missing_tree(src, dst);
        } else if (S_ISREG(st.st_mode) && !file_has_content(dst)) {
            ensure_parent_dirs(dst);
            if (copy_file(src, dst)) ++copied;
        }
    }

    closedir(dir);
    return copied;
}

// Picks the card root, creates it, and moves an internal card over if there is one.
// Returns an empty string when neither directory is usable.
std::string prepare_sd_root(const char* filesDir, const char* externalFilesDir) {
    const bool hasFilesDir = filesDir != nullptr && filesDir[0] != '\0';
    const bool hasExternal = externalFilesDir != nullptr && externalFilesDir[0] != '\0';

    std::string sd;
    if (hasExternal) {
        sd = std::string(externalFilesDir) + kSdcardSubdir;
    } else if (hasFilesDir) {
        sd = std::string(filesDir) + kSdcardSubdir;
        LOGW("sdcard: no external files directory on this device, the card stays in %s",
             sd.c_str());
    } else {
        return std::string();
    }

    ensure_dir(sd);

    if (hasFilesDir) {
        const std::string internal = std::string(filesDir) + kSdcardSubdir;
        if (internal != sd) {
            const unsigned moved = copy_missing_tree(internal, sd);
            if (moved > 0) {
                LOGI("sdcard: %u file(s) taken over from %s", moved, internal.c_str());
            }
        }
    }

    return sd;
}

// Recompute how the LCD frame maps onto the window (aspect-fit + centred).
void update_transform(int32_t winW, int32_t winH) {
    const int32_t sx = (winW * kFp) / g_lcdW;
    const int32_t sy = (winH * kFp) / g_lcdH;
    g_scaleFP = std::max<int32_t>(1, std::min(sx, sy));

    g_scaledW = (g_lcdW * g_scaleFP) / kFp;
    const int32_t scaledH = (g_lcdH * g_scaleFP) / kFp;
    g_offX = (winW - g_scaledW) / 2;
    g_offY = (winH - scaledH) / 2;

    g_srcX.assign(static_cast<size_t>(g_scaledW), 0);
    for (int32_t d = 0; d < g_scaledW; ++d) {
        int32_t x = (d * kFp) / g_scaleFP;
        if (x < 0) x = 0;
        if (x >= g_lcdW) x = g_lcdW - 1;
        g_srcX[static_cast<size_t>(d)] = x;
    }

    LOGI("window %dx%d -> LCD %dx%d scale %d/1024 offset %d,%d", winW, winH, g_lcdW,
         g_lcdH, g_scaleFP, g_offX, g_offY);
}

// Push the current LCD frame to the window, letterboxed in black.
void blit() {
    ANativeWindow* window = g_window.load();
    if (window == nullptr || g_frame.empty()) return;

    ANativeWindow_Buffer buffer;
    if (ANativeWindow_lock(window, &buffer, nullptr) != 0) return;

    const uint16_t* src = g_frame.data();
    for (int32_t y = 0; y < buffer.height; ++y) {
        uint16_t* dst =
            reinterpret_cast<uint16_t*>(buffer.bits) + static_cast<size_t>(y) * buffer.stride;

        const int32_t srcY = ((y - g_offY) * kFp) / g_scaleFP;
        if (srcY < 0 || srcY >= g_lcdH) {
            std::memset(dst, 0, sizeof(uint16_t) * static_cast<size_t>(buffer.width));
            continue;
        }

        const uint16_t* srcRow = src + static_cast<size_t>(srcY) * g_lcdW;
        int32_t x = 0;
        for (; x < g_offX && x < buffer.width; ++x) dst[x] = 0;
        for (int32_t d = 0; d < g_scaledW && x < buffer.width; ++d, ++x) {
            dst[x] = srcRow[g_srcX[static_cast<size_t>(d)]];
        }
        for (; x < buffer.width; ++x) dst[x] = 0;
    }

    ANativeWindow_unlockAndPost(window);
}

// ------------------------------------------------------------------ link ---
//
// The firmware and everything that feeds it. Owned by RcLinkService, running
// whether or not the activity has a window.

bool link_running() { return g_linkRunning.load(); }

// Drives the parts of the firmware that need a periodic kick while the activity
// is not there to do it.
//
// Deliberately NOT consuming LCD frames: takeFrame() ends in lcdFlushed(), which
// calls lv_disp_flush_ready() inside the firmware - LVGL state that only the
// thread owning the window should touch. While no window is attached the firmware
// simply parks after its last flush (its mixer and module tasks keep running, so
// frames keep going to the RF module), and the next takeFrame() from the activity
// lets it render again.
void link_thread_main() {
    using clock = std::chrono::steady_clock;
    auto nextHeartbeat = clock::now() + std::chrono::seconds(5);
    bool loggedOnce = false;

    while (!g_linkStop.load()) {
        joystick::tick();

        const auto now = clock::now();
        if (now >= nextHeartbeat) {
            nextHeartbeat = now + std::chrono::seconds(10);

            // Proof of life in logcat, and the only way to tell from outside
            // whether the link really survived the UI going away.
            LOGI("link: firmware %s, module tx %u B rx %u B dropped %u B, port %s, window %s",
                 simu::running() ? "running" : "stopped", module_serial::txBytes(),
                 module_serial::rxBytes(), module_serial::droppedBytes(),
                 module_serial::portOpen() ? "open" : "closed",
                 g_window.load() != nullptr ? "attached" : "detached");

            if (!loggedOnce) {
                loggedOnce = true;
                // Says which protocol drives the external module port (ModuleType:
                // 0 none, 1 ppm, 2 xjt, 3 isrm, 4 dsm2, 5 crsf, 6 multimodule). 0 means
                // the model has the slot switched off, and then EdgeTX never opens it -
                // no bytes will flow however well the USB serial link itself is working.
                LOGI("module: external RF protocol = %u (0 off, 5 crsf)",
                     static_cast<unsigned>(simu::externalModuleType()));
                // The ADC driver tables exist by now, so the firmware's own battery
                // reading can be logged next to what the RC reports.
                simu::logFirmwareBattery();
            }
        }

        sleep_ms(8);  // ~120 Hz, same cadence the activity loop used
    }
}

// Starts the firmware and its module bridge. Idempotent, and callable from either
// the service (the normal path) or the activity (fallback, see android_main).
bool link_start(AAssetManager* assets, const char* filesDir, const char* externalFilesDir) {
    std::lock_guard<std::mutex> lock(g_linkMutex);
    if (g_linkRunning.load()) return true;

    // Where the firmware sees its SD card, and where the user can edit it. The
    // external directory is preferred - see prepare_sd_root().
    const std::string sd = prepare_sd_root(filesDir, externalFilesDir);
    if (sd.empty()) {
        LOGE("link: no directory to hold the simulated SD card");
        return false;
    }
    LOGI("sdcard: root %s (push files into it to edit the card, no reboot needed)",
         sd.c_str());

    if (assets != nullptr) {
        seed_assets(assets, sd);
    }

    const simu::LcdInfo lcd = simu::lcdInfo();
    {
        // blit() reads the LCD geometry: never let it see a half-updated value.
        std::lock_guard<std::mutex> renderLock(g_renderMutex);
        g_lcdW = lcd.width;
        g_lcdH = lcd.height;
    }
    if (g_lcdW <= 0 || g_lcdH <= 0) {
        LOGE("link: bad LCD size %dx%d", g_lcdW, g_lcdH);
        return false;
    }

    // The firmware's analog channels belong to this app, never to the simulator's
    // demo sine wave. Until the first real value arrives the firmware would
    // otherwise drive every stick with 2048 + sin(...)*900, so the sticks visibly
    // flail around for the seconds it takes the DJI SDK to start reporting.
    // Switching the source here makes the channels read a centred 2048 instead.
    simu::setAnalogSource(true);

    // Install the external RF module serial bridge before the firmware boots: it
    // opens the module port on the mixer task and would otherwise start sending
    // frames into nothing.
    module_serial::init();

    if (!simu::start(sd.c_str(), sd.c_str())) {
        LOGE("link: failed to start the EdgeTX simulator");
        return false;
    }

    g_linkStop.store(false);
    g_linkThread = std::thread(link_thread_main);
    g_linkRunning.store(true);

    LOGI("link: EdgeTX host started (sd=%s)", sd.c_str());
    return true;
}

// Stops the firmware. Only called when nothing is left to keep the link alive.
void link_stop() {
    std::lock_guard<std::mutex> lock(g_linkMutex);
    if (!g_linkRunning.load() && !g_linkThread.joinable()) return;

    g_linkStop.store(true);
    if (g_linkThread.joinable()) g_linkThread.join();

    // No render can be in flight while the firmware is torn down underneath it.
    {
        std::lock_guard<std::mutex> renderLock(g_renderMutex);
        simu::stop();
    }
    g_linkRunning.store(false);
    LOGI("link: stopped");
}

// --------------------------------------------------------------- window ------
//
// The activity side of the link: attach while visible, detach when the UI goes
// away. Neither touches the firmware.

// Returns false when the window is not usable yet; android_main retries.
bool window_attach(ANativeWindow* window) {
    if (window == nullptr) return false;

    const int32_t winW = ANativeWindow_getWidth(window);
    const int32_t winH = ANativeWindow_getHeight(window);
    if (winW <= 0 || winH <= 0) {
        // APP_CMD_INIT_WINDOW can arrive before the surface has a size.
        LOGW("window: no size yet (%dx%d)", winW, winH);
        return false;
    }

    if (ANativeWindow_setBuffersGeometry(window, winW, winH, WINDOW_FORMAT_RGB_565) != 0) {
        LOGE("window: ANativeWindow_setBuffersGeometry failed");
        return false;
    }

    const simu::LcdInfo lcd = simu::lcdInfo();
    if (lcd.width <= 0 || lcd.height <= 0) {
        LOGE("window: bad LCD size %dx%d", lcd.width, lcd.height);
        return false;
    }

    std::lock_guard<std::mutex> renderLock(g_renderMutex);
    g_lcdW = lcd.width;
    g_lcdH = lcd.height;
    g_frame.assign(static_cast<size_t>(g_lcdW) * g_lcdH, 0);
    update_transform(winW, winH);
    g_window.store(window);

    LOGI("window: attached (%dx%d)", winW, winH);
    return true;
}

// The buffers stay allocated on purpose: the render step reads them and a window
// can come back at any time, so tearing them down here would only create a
// lifetime problem for no gain.
void window_detach() {
    std::lock_guard<std::mutex> renderLock(g_renderMutex);
    if (g_window.exchange(nullptr) == nullptr) return;

    // Deliberately not touching the firmware: the RF module still needs its frames.
    LOGI("window: detached, the link keeps running");
}

// ------------------------------------------------------------ app callbacks --

void on_app_cmd(struct android_app* app, int32_t cmd) {
    (void)app;
    switch (cmd) {
        case APP_CMD_INIT_WINDOW:
            // Attaching can fail while the surface has no size; android_main retries.
            if (g_app != nullptr && g_app->window != nullptr) window_attach(g_app->window);
            break;
        case APP_CMD_TERM_WINDOW:
            // The window going away must not stop the firmware: RcLinkService keeps
            // the module fed on purpose.
            window_detach();
            break;
        default:
            break;
    }
}

int32_t on_input_event(struct android_app* app, AInputEvent* event) {
    (void)app;
    const int32_t type = AInputEvent_getType(event);

    // Buttons on a hardware controller (gamepad, or an RC transmitter that
    // enumerates as one) become EdgeTX key presses.
    if (type == AINPUT_EVENT_TYPE_KEY) {
        if (joystick::handleKeyEvent(event)) return 1;
        return 0;
    }

    if (type != AINPUT_EVENT_TYPE_MOTION) return 0;

    // Axes from the same controllers drive the firmware's analog channels. The
    // stick event has to be consumed here: every MotionEvent carries an X/Y
    // pair, so it would otherwise be interpreted as a touch somewhere on the
    // LCD.
    if (joystick::handleMotionEvent(event)) return 1;

    // Only a real touchscreen drives EdgeTX's touch input. A mouse or any other
    // pointer device must not be turned into taps on the LCD.
    if ((AInputEvent_getSource(event) & AINPUT_SOURCE_TOUCHSCREEN) !=
        AINPUT_SOURCE_TOUCHSCREEN) {
        return 0;
    }

    // No window means no touch anyway; the firmware may well still be up.
    if (g_window.load() == nullptr || g_lcdW <= 0) return 0;

    const int32_t action = AMotionEvent_getAction(event);
    const int32_t action_code = action & AMOTION_EVENT_ACTION_MASK;

    const float wx = AMotionEvent_getX(event, 0);
    const float wy = AMotionEvent_getY(event, 0);
    int32_t lx = (static_cast<int32_t>(wx) - g_offX) * kFp / g_scaleFP;
    int32_t ly = (static_cast<int32_t>(wy) - g_offY) * kFp / g_scaleFP;
    lx = std::clamp(lx, 0, g_lcdW - 1);
    ly = std::clamp(ly, 0, g_lcdH - 1);

    switch (action_code) {
        case AMOTION_EVENT_ACTION_DOWN:
        case AMOTION_EVENT_ACTION_POINTER_DOWN:
        case AMOTION_EVENT_ACTION_MOVE:
            // Repeated position updates during a drag: the firmware detects
            // slides from successive changes.
            simu::touchDown(static_cast<int16_t>(lx), static_cast<int16_t>(ly));
            break;
        case AMOTION_EVENT_ACTION_UP:
        case AMOTION_EVENT_ACTION_POINTER_UP:
        case AMOTION_EVENT_ACTION_CANCEL:
            simu::touchUp();
            break;
        default:
            break;
    }
    return 1;
}

}  // namespace

extern "C" void android_main(struct android_app* app) {
    g_app = app;
    app->onAppCmd = on_app_cmd;
    app->onInputEvent = on_input_event;

    LOGI("native_main: activity started (%u bundled sdcard assets)", kSdcardAssetCount);

    while (!app->destroyRequested) {
        // Drain pending Android lifecycle / input events.
        while (true) {
            int events;
            struct android_poll_source* source;
            const int ident =
                ALooper_pollOnce(0, nullptr, &events, reinterpret_cast<void**>(&source));
            if (ident < 0) break;
            if (source != nullptr) source->process(app, source);
            if (app->destroyRequested) break;
        }
        if (app->destroyRequested) break;

        // Normally RcLinkService started the firmware already (it is started from
        // Application.onCreate). This is the fallback for when the service could not
        // be started at all: a UI without a service is better than a black screen.
        if (!link_running() && app->activity != nullptr) {
            link_start(app->activity->assetManager, app->activity->internalDataPath,
                       app->activity->externalDataPath);
        }

        // A window that was not usable when APP_CMD_INIT_WINDOW arrived makes
        // window_attach() bail out, and nothing else would ever call it again: the app
        // would sit on a black screen for good. Keep retrying while the window is up.
        if (g_window.load() == nullptr && app->window != nullptr) {
            if (window_attach(app->window) && app->activity != nullptr) {
                // Report the input devices once so logcat shows whether this device
                // exposes its sticks to Android at all (many vendor remote
                // controllers do not). Only meaningful with a window: only a focused
                // window receives their input events.
                joystick::init(app->activity);

                // Show the newest frame we hold straight away. The firmware may be
                // sitting on a screen that only repaints on input, so waiting for the
                // next frame would leave the window black until the user presses
                // something.
                std::lock_guard<std::mutex> renderLock(g_renderMutex);
                if (!g_frame.empty()) blit();
            }
        }

        // Present a new firmware frame when one is ready. joystick::tick() lives on
        // the link thread - see link_thread_main() - but the frames are consumed here
        // and only here, because takeFrame() ends inside LVGL (lcdFlushed() ->
        // lv_disp_flush_ready()), which belongs to the thread that owns the window.
        // Frames are taken even while no window is attached. RcLinkService starts the
        // firmware from Application.onCreate, so it paints its first screens before the
        // activity has a surface; those frames were previously dropped, and the firmware
        // then only paints again on an input event - which is exactly why the screen
        // used to stay black until a key was pressed.
        if (link_running()) {
            std::lock_guard<std::mutex> renderLock(g_renderMutex);
            if (!g_frame.empty()) {
                const bool fresh =
                    simu::takeFrame(reinterpret_cast<uint8_t*>(g_frame.data()),
                                    static_cast<uint32_t>(g_frame.size() * sizeof(uint16_t)));
                if (fresh && g_window.load() != nullptr) blit();
            }
        }

        sleep_ms(8);  // ~120 Hz poll, cheap while the firmware idles
    }

    // The activity is going away. The link only stops with it when nothing is
    // holding the process open: with RcLinkService up, the firmware (and with it the
    // stick data reaching the external RF module) survives the UI, and the next
    // launch attaches to the same running firmware.
    window_detach();
    if (g_keepAlive.load()) {
        LOGI("native_main: activity exit, the link stays up");
    } else {
        link_stop();
        LOGI("native_main: activity exit, the link stops with it");
    }
}

// ------------------------------------------------------- service entry points --
// Called from RcLinkService.java.

// Starts the firmware on behalf of the service and marks the process as "keep me
// alive": android_main only stops the link when this flag is clear.
//
// `externalFilesDir` is the app's external files directory (shared storage); the
// simulated SD card is put there so it can be edited from outside the app. When it
// is null the internal directory is used instead.
extern "C" JNIEXPORT jboolean JNICALL
Java_com_edgetx_droidui_RcLinkService_nativeStartLink(JNIEnv* env, jclass, jstring filesDir,
                                                      jstring externalFilesDir, jobject assets) {
    const char* dir = nullptr;
    if (filesDir != nullptr) {
        dir = env->GetStringUTFChars(filesDir, nullptr);
    }

    const char* external = nullptr;
    if (externalFilesDir != nullptr) {
        external = env->GetStringUTFChars(externalFilesDir, nullptr);
    }

    // AAssetManager_fromJava returns the manager the activity used to expose as
    // ANativeActivity::assetManager, which is where the bundled SD card is read from.
    AAssetManager* manager = assets != nullptr ? AAssetManager_fromJava(env, assets) : nullptr;

    g_keepAlive.store(true);
    const bool ok = link_start(manager, dir, external);

    if (dir != nullptr) {
        env->ReleaseStringUTFChars(filesDir, dir);
    }
    if (external != nullptr) {
        env->ReleaseStringUTFChars(externalFilesDir, external);
    }
    return ok ? JNI_TRUE : JNI_FALSE;
}

extern "C" JNIEXPORT void JNICALL
Java_com_edgetx_droidui_RcLinkService_nativeStopLink(JNIEnv*, jclass) {
    g_keepAlive.store(false);
    link_stop();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_edgetx_droidui_RcLinkService_nativeLinkRunning(JNIEnv*, jclass) {
    return link_running() ? JNI_TRUE : JNI_FALSE;
}
