// NativeActivity entry point: a thin host for the ported EdgeTX simulator.
//
// Everything the user sees is the real EdgeTX firmware running inside
// libedgetx-<flavour>-simulator.so. This file only:
//   * seeds the simulated SD card from the APK assets on first run,
//   * owns the ANativeWindow and blits the firmware's LCD frames to it,
//   * forwards touch events into the firmware as LCD coordinates.
//
// See simu_host.{h,cpp} for the firmware lifecycle, and
// radio/src/targets/simu/simulib.h for the platform API being used.
#include <android/asset_manager.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android_native_app_glue.h>
#include <sys/stat.h>

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <thread>
#include <vector>

#include "joystick.h"
#include "log.h"
#include "sdcard_manifest.h"  // generated by CMake from assets/sdcard
#include "simu_host.h"

namespace {

constexpr int32_t kFp = 1024;  // fixed-point scale denominator

struct android_app* g_app = nullptr;
ANativeWindow* g_window = nullptr;

int32_t g_lcdW = 0;
int32_t g_lcdH = 0;

// LCD -> window mapping.
int32_t g_scaleFP = kFp;
int32_t g_scaledW = 0;
int32_t g_offX = 0;
int32_t g_offY = 0;
std::vector<int32_t> g_srcX;

std::vector<uint16_t> g_frame;  // LCD frame buffer (RGB565)

bool g_uiRunning = false;

uint64_t now_ms() {
    using clock = std::chrono::steady_clock;
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::milliseconds>(clock::now().time_since_epoch())
            .count());
}

void sleep_ms(uint32_t ms) {
    std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

void ensure_dir(const std::string& path) {
    if (!path.empty()) mkdir(path.c_str(), 0700);
}

// mkdir -p for the slash separated parents of `path`.
void ensure_parent_dirs(const std::string& path) {
    for (size_t i = 1; i < path.size(); ++i) {
        if (path[i] == '/') mkdir(path.substr(0, i).c_str(), 0700);
    }
}

// Copy the bundled SD-card content into the simulated card root.
//
// The file list comes from the manifest CMake generated (AAssetDir enumeration
// proved unreliable). Existing files with the expected size are skipped, so this
// is idempotent and never clobbers what the firmware wrote (radio.yml, models).
void seed_assets(AAssetManager* mgr, const std::string& sdRoot) {
    unsigned copied = 0;
    unsigned skipped = 0;

    for (unsigned i = 0; i < kSdcardAssetCount; ++i) {
        const std::string rel = kSdcardAssets[i];
        const std::string assetPath = "sdcard/" + rel;
        const std::string outPath = sdRoot + "/" + rel;

        AAsset* asset = AAssetManager_open(mgr, assetPath.c_str(), AASSET_MODE_STREAMING);
        if (asset == nullptr) {
            LOGE("asset missing: %s", assetPath.c_str());
            continue;
        }

        const off_t size = AAsset_getLength(asset);

        struct stat st;
        if (stat(outPath.c_str(), &st) == 0 && st.st_size == size) {
            AAsset_close(asset);
            ++skipped;
            continue;
        }

        ensure_parent_dirs(outPath);

        std::vector<uint8_t> buf(size > 0 ? static_cast<size_t>(size) : 0);
        const int got = size > 0 ? AAsset_read(asset, buf.data(), static_cast<size_t>(size)) : 0;
        AAsset_close(asset);

        FILE* out = std::fopen(outPath.c_str(), "wb");
        if (out == nullptr) {
            LOGE("cannot write %s", outPath.c_str());
            continue;
        }
        if (got > 0) std::fwrite(buf.data(), 1, static_cast<size_t>(got), out);
        std::fclose(out);
        ++copied;
    }

    LOGI("sdcard: %u copied, %u up-to-date, %u total", copied, skipped, kSdcardAssetCount);
}

// Recompute how the LCD frame maps onto the window (aspect-fit + centred).
void update_transform(int32_t winW, int32_t winH) {
    const int32_t sx = (winW * kFp) / g_lcdW;
    const int32_t sy = (winH * kFp) / g_lcdH;
    g_scaleFP = std::max<int32_t>(1, std::min(sx, sy));

    g_scaledW = (g_lcdW * g_scaleFP) / kFp;
    const int32_t scaledH = (g_lcdH * g_scaleFP) / kFp;
    g_offX = (winW - g_scaledW) / 2;
    g_offY = (winH - scaledH) / 2;

    g_srcX.assign(static_cast<size_t>(g_scaledW), 0);
    for (int32_t d = 0; d < g_scaledW; ++d) {
        int32_t x = (d * kFp) / g_scaleFP;
        if (x < 0) x = 0;
        if (x >= g_lcdW) x = g_lcdW - 1;
        g_srcX[static_cast<size_t>(d)] = x;
    }

    LOGI("window %dx%d -> LCD %dx%d scale %d/1024 offset %d,%d", winW, winH, g_lcdW,
         g_lcdH, g_scaleFP, g_offX, g_offY);
}

// Push the current LCD frame to the window, letterboxed in black.
void blit() {
    if (g_window == nullptr || g_frame.empty()) return;

    ANativeWindow_Buffer buffer;
    if (ANativeWindow_lock(g_window, &buffer, nullptr) != 0) return;

    const uint16_t* src = g_frame.data();
    for (int32_t y = 0; y < buffer.height; ++y) {
        uint16_t* dst =
            reinterpret_cast<uint16_t*>(buffer.bits) + static_cast<size_t>(y) * buffer.stride;

        const int32_t srcY = ((y - g_offY) * kFp) / g_scaleFP;
        if (srcY < 0 || srcY >= g_lcdH) {
            std::memset(dst, 0, sizeof(uint16_t) * static_cast<size_t>(buffer.width));
            continue;
        }

        const uint16_t* srcRow = src + static_cast<size_t>(srcY) * g_lcdW;
        int32_t x = 0;
        for (; x < g_offX && x < buffer.width; ++x) dst[x] = 0;
        for (int32_t d = 0; d < g_scaledW && x < buffer.width; ++d, ++x) {
            dst[x] = srcRow[g_srcX[static_cast<size_t>(d)]];
        }
        for (; x < buffer.width; ++x) dst[x] = 0;
    }

    ANativeWindow_unlockAndPost(g_window);
}

void ui_start() {
    if (g_uiRunning) return;
    if (g_app == nullptr || g_app->window == nullptr || g_app->activity == nullptr) return;

    g_window = g_app->window;
    const int32_t winW = ANativeWindow_getWidth(g_window);
    const int32_t winH = ANativeWindow_getHeight(g_window);
    if (winW <= 0 || winH <= 0) return;

    if (ANativeWindow_setBuffersGeometry(g_window, winW, winH, WINDOW_FORMAT_RGB_565) != 0) {
        LOGE("ANativeWindow_setBuffersGeometry failed");
        return;
    }

    // App-private storage for the simulated SD card. Externally the firmware
    // sees this directory as the card root (RADIO/, MODELS/, THEMES/, ...).
    const std::string base = g_app->activity->internalDataPath != nullptr
                                 ? g_app->activity->internalDataPath
                                 : "/data/local/tmp";
    const std::string sd = base + "/sdcard";
    ensure_dir(sd);

    if (g_app->activity->assetManager != nullptr) {
        seed_assets(g_app->activity->assetManager, sd);
    }

    const simu::LcdInfo lcd = simu::lcdInfo();
    g_lcdW = lcd.width;
    g_lcdH = lcd.height;
    if (g_lcdW <= 0 || g_lcdH <= 0) {
        LOGE("bad LCD size %dx%d", g_lcdW, g_lcdH);
        return;
    }
    g_frame.assign(static_cast<size_t>(g_lcdW) * g_lcdH, 0);
    update_transform(winW, winH);

    if (!simu::start(sd.c_str(), sd.c_str())) {
        LOGE("failed to start the EdgeTX simulator");
        return;
    }

    // Report the input devices once so logcat shows whether this device exposes
    // its sticks to Android at all (many vendor remote controllers do not).
    joystick::init(g_app->activity);

    g_uiRunning = true;
    LOGI("EdgeTX host started (%dx%d window)", winW, winH);
}

void ui_stop() {
    if (!g_uiRunning) return;

    simu::stop();
    g_uiRunning = false;
    g_window = nullptr;
    g_frame.clear();
    g_srcX.clear();
    LOGI("EdgeTX host stopped");
}

// ------------------------------------------------------------ app callbacks --

void on_app_cmd(struct android_app* app, int32_t cmd) {
    (void)app;
    switch (cmd) {
        case APP_CMD_INIT_WINDOW:
            if (g_app != nullptr && g_app->window != nullptr) ui_start();
            break;
        case APP_CMD_TERM_WINDOW:
            ui_stop();
            break;
        default:
            break;
    }
}

int32_t on_input_event(struct android_app* app, AInputEvent* event) {
    (void)app;
    if (AInputEvent_getType(event) != AINPUT_EVENT_TYPE_MOTION) return 0;

    // A hardware joystick (gamepad, or an RC transmitter enumerating as a HID
    // joystick) drives the firmware's analog channels. It has to be consumed
    // here: every MotionEvent carries an X/Y pair, so a stick event would
    // otherwise be interpreted as a touch somewhere on the LCD.
    if (joystick::handleMotionEvent(event)) return 1;

    if (!g_uiRunning || g_lcdW <= 0) return 0;

    const int32_t action = AMotionEvent_getAction(event);
    const int32_t action_code = action & AMOTION_EVENT_ACTION_MASK;

    const float wx = AMotionEvent_getX(event, 0);
    const float wy = AMotionEvent_getY(event, 0);
    int32_t lx = (static_cast<int32_t>(wx) - g_offX) * kFp / g_scaleFP;
    int32_t ly = (static_cast<int32_t>(wy) - g_offY) * kFp / g_scaleFP;
    lx = std::clamp(lx, 0, g_lcdW - 1);
    ly = std::clamp(ly, 0, g_lcdH - 1);

    switch (action_code) {
        case AMOTION_EVENT_ACTION_DOWN:
        case AMOTION_EVENT_ACTION_POINTER_DOWN:
        case AMOTION_EVENT_ACTION_MOVE:
            // Repeated position updates during a drag: the firmware detects
            // slides from successive changes.
            simu::touchDown(static_cast<int16_t>(lx), static_cast<int16_t>(ly));
            break;
        case AMOTION_EVENT_ACTION_UP:
        case AMOTION_EVENT_ACTION_POINTER_UP:
        case AMOTION_EVENT_ACTION_CANCEL:
            simu::touchUp();
            break;
        default:
            break;
    }
    return 1;
}

}  // namespace

extern "C" void android_main(struct android_app* app) {
    g_app = app;
    app->onAppCmd = on_app_cmd;
    app->onInputEvent = on_input_event;

    LOGI("native_main: starting EdgeTX host (%u bundled sdcard assets)",
         kSdcardAssetCount);

    while (!app->destroyRequested) {
        // Drain pending Android lifecycle / input events.
        while (true) {
            int events;
            struct android_poll_source* source;
            const int ident =
                ALooper_pollOnce(0, nullptr, &events, reinterpret_cast<void**>(&source));
            if (ident < 0) break;
            if (source != nullptr) source->process(app, source);
            if (app->destroyRequested) break;
        }
        if (app->destroyRequested) break;

        // Present a new firmware frame when one is ready.
        if (g_uiRunning && g_window != nullptr) {
            if (simu::takeFrame(reinterpret_cast<uint8_t*>(g_frame.data()),
                                static_cast<uint32_t>(g_frame.size() * sizeof(uint16_t)))) {
                blit();
            }
        }

        sleep_ms(8);  // ~120 Hz poll, cheap while the firmware idles
    }

    ui_stop();
    LOGI("native_main: exit");
}
